# Generated by Django 4.2.8 on 2023-12-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mahsulot_nomi', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('Mahsulot_narhi', models.CharField(max_length=10, verbose_name='Mahsulot narhi')),
                ('Mahsulot_rasmi', models.CharField(max_length=300, verbose_name='Mahsulot rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID')),
            ],
        ),
    ]
