# Generated by Django 4.0.4 on 2023-12-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Mahsulot_narhi',
            new_name='narhi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Mahsulot_nomi',
            new_name='nomi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Mahsulot_rasmi',
            new_name='rasmi',
        ),
    ]
